### ISSUE TITLE
Disable ban list check

### ISSUE THREAD

**Issue by zplesac** [infinum/android-complexify#4]
Currently, there is no way to disable ban list check, which is bad. If we call setBanList(null), an NPE will be thrown, which is even worse.

I suggest that we add one more method, with which we can define whether we want to check if password is in the ban list.

Also, we need to fix NPE with _null_ banList.

**Comment by dmarusic35** [comment]
Thanks for reporting @zplesac. I've fixed NPE and also added method as you proposed. 
You can find it in #5 and release 2.0.1
